language: scala
scala:
  - 2.11.12
  - 2.12.10
jdk:
  - openjdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      sbt ++$TRAVIS_SCALA_VERSION publish;
      fi
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
